version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "5 minutes"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/llvm/docs"
    schedule:
      interval: "5 minutes"
    groups:
      llvm-docs-requirements:
        patterns:
          - "*"
